### ISSUE TITLE
Upgrading to latest version of docusaurus v2 will break config, highlightutils and more

### ISSUE THREAD

**Issue by tvvignesh** [timberio/vector-website#70]
Hi there. Since I am using this project as a base template for things I am working on, I thought I should let you guys know. If you upgrade to latest version of docusaurus, there are quite a few breaking changes.

For instance `parse` has been changed to `parseMarkdownFile` in utils, config options have been renamed and there are more changes to look out for when upgrading (test with `"@docusaurus/core": "^2.0.0-alpha.61"`)

**Comment by tvvignesh** [comment]
Nvm. Saw this: https://github.com/timberio/vector-website/issues/3 Closing this issue. Thanks

**Comment by jszwedko** [comment]
Thanks for the heads up though! That was thoughtful.
